name: 'Setup CI'
description: 'Setup Node.js, pnpm, and install dependencies with optional caching'

inputs:
  enable-nextjs-cache:
    description: 'Enable Next.js build cache'
    required: false
    default: 'false'
  enable-typescript-cache:
    description: 'Enable TypeScript incremental cache'
    required: false
    default: 'false'
  enable-vitest-cache:
    description: 'Enable Vitest cache'
    required: false
    default: 'false'
  enable-playwright-cache:
    description: 'Enable Playwright browser cache'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Cache Next.js build
      if: inputs.enable-nextjs-cache == 'true'
      uses: actions/cache@v4
      with:
        path: .next/cache
        key: nextjs-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('src/**/*.ts', 'src/**/*.tsx') }}
        restore-keys: |
          nextjs-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-
          nextjs-${{ runner.os }}-

    - name: Cache TypeScript build info
      if: inputs.enable-typescript-cache == 'true'
      uses: actions/cache@v4
      with:
        path: .tsbuildinfo
        key: tsbuildinfo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('src/**/*.ts', 'src/**/*.tsx') }}
        restore-keys: |
          tsbuildinfo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-
          tsbuildinfo-${{ runner.os }}-

    - name: Cache Vitest
      if: inputs.enable-vitest-cache == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules/.vitest
        key: vitest-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Cache Playwright browsers
      if: inputs.enable-playwright-cache == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
